title: Mallory Freeberg, PhD (she/her)
logo: /assets/img/headshot.jpg
description: Collaboration Builder | Bioinformatics & Metadata Enthusiast | Open Science Advocate
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
