title: Mallory Freeberg, PhD
logo: /assets/img/headshot.jpg
description: Collaboration Builder | Bioinformatics & Metadata Enthusiast | Open Science Advocate | she/her
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
