title: Mallory Freeberg, PhD (she/her)
logo: /assets/img/headshot.jpg
description: Bioinformatics & Metadata Enthusiast | Collaboration Builder | Open Science Advocate
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
